from pathlib import Path
from typing import Any

from mflux.utils.version_util import VersionUtil


class ModelCardSaver:
    CONTRIBUTOR = "[@lpalbou](https://huggingface.co/lpalbou)"
    DEFAULT_NAMESPACE = "AbstractFramework"
    PROJECT_URL = "https://github.com/lpalbou/mlx-gen"
    QUANTIZATION_DOC_URL = "https://github.com/lpalbou/mlx-gen/blob/main/docs/quantization.md"
    FLUX_NON_COMMERCIAL_LICENSE_NAME = "flux-non-commercial-license"
    FLUX_NON_COMMERCIAL_LICENSE_DISPLAY_NAME = "FLUX Non-Commercial License"
    FLUX_NON_COMMERCIAL_LICENSE_LINK = "https://huggingface.co/black-forest-labs/FLUX.2-klein-9B/blob/main/LICENSE.md"
    FLUX_ACCEPTABLE_USE_POLICY_LINK = "https://bfl.ai/legal/usage-policy"

    @staticmethod
    def save_model_card(base_path: str, model: Any, bits: int | None) -> None:
        path = Path(base_path)
        path.mkdir(parents=True, exist_ok=True)
        (path / "README.md").write_text(
            ModelCardSaver.render_model_card(
                base_path=base_path,
                model=model,
                bits=bits,
            ),
            encoding="utf-8",
        )

    @staticmethod
    def render_model_card(base_path: str, model: Any, bits: int | None) -> str:
        model_name = ModelCardSaver._model_name(model)
        terms = ModelCardSaver._model_terms(model)
        repo_name = Path(base_path).name or ModelCardSaver._repo_name(model_name)
        repo_id = f"{ModelCardSaver.DEFAULT_NAMESPACE}/{repo_name}"
        pipeline_tag = ModelCardSaver._pipeline_tag(terms)
        tags = ModelCardSaver._tags(terms, bits, pipeline_tag)
        frontmatter = ModelCardSaver._frontmatter(model_name, terms, pipeline_tag, tags)

        sections = [
            frontmatter,
            f"# {repo_name}",
            "",
            (
                f"This repository contains MLX-Gen saved weights for `{model_name}`. "
                "The checkpoint is designed for local Apple Silicon inference with "
                f"[`mlx-gen`]({ModelCardSaver.PROJECT_URL})."
            ),
            "",
            ModelCardSaver._layout_sentence(bits),
            "",
            "## Source Model",
            "",
            ModelCardSaver._source_model_line(model_name),
            "",
            *ModelCardSaver._license_section(model_name, terms, bits),
            "",
            "## Quantization",
            "",
            ModelCardSaver._quantization_section(terms, bits),
            "",
            "## Compatibility",
            "",
            f"Requires `mlx-gen >= {VersionUtil.get_mflux_version()}`.",
            "",
            f"Generated with `mlx-gen {VersionUtil.get_mflux_version()}`.",
            "",
            ModelCardSaver._command_surface_line(terms),
            "",
            "## Usage",
            "",
            *ModelCardSaver._usage_note(terms, bits),
            *ModelCardSaver._usage_block(repo_id, pipeline_tag, terms, bits),
            "",
            "## Attribution",
            "",
            "MLX-Gen is based on [mflux](https://github.com/filipstrand/mflux) by "
            "Filip Strand and the original mflux contributors. This model card is "
            "generated by MLX-Gen so derived checkpoints keep that attribution visible.",
            "",
            ModelCardSaver._contributor_line(bits),
            "",
        ]
        return "\n".join(sections)

    @staticmethod
    def _frontmatter(model_name: str, terms: str, pipeline_tag: str, tags: list[str]) -> str:
        lines = [
            "---",
        ]
        lines.extend(ModelCardSaver._license_frontmatter(model_name, terms))
        lines.extend(
            [
                f"base_model: {model_name}",
                f"pipeline_tag: {pipeline_tag}",
                "library_name: mlx-gen",
                "tags:",
            ]
        )
        lines.extend([f"- {tag}" for tag in tags])
        lines.append("---")
        return "\n".join(lines)

    @staticmethod
    def _license_frontmatter(model_name: str, terms: str) -> list[str]:
        if ModelCardSaver._is_fibo_model(model_name, terms):
            return [
                "license: other",
                "license_name: bria-fibo",
                f"license_link: {ModelCardSaver._fibo_license_link(model_name)}",
                (
                    'extra_gated_prompt: "Access is for non-commercial use under the '
                    "Bria FIBO license. This repository is a quantized derivative of "
                    'the gated briaai/FIBO source model."'
                ),
                "extra_gated_fields:",
                "  I agree to use this model for non-commercial use only: checkbox",
                "  I agree to follow the Bria FIBO license terms: checkbox",
            ]

        if ModelCardSaver._is_flux2_9b(model_name, terms):
            return [
                "license: other",
                f"license_name: {ModelCardSaver.FLUX_NON_COMMERCIAL_LICENSE_NAME}",
                f"license_link: {ModelCardSaver._flux_noncommercial_license_link(model_name)}",
                (
                    'extra_gated_prompt: "Access is for non-commercial use under the '
                    "FLUX Non-Commercial License and Black Forest Labs Acceptable Use Policy. "
                    "This repository is a quantized derivative of a gated Black Forest Labs "
                    'FLUX.2 Klein 9B model."'
                ),
                "extra_gated_fields:",
                "  I agree to use this model for non-commercial use only: checkbox",
                "  I agree to follow the FLUX Non-Commercial License: checkbox",
                "  I acknowledge the Black Forest Labs Acceptable Use Policy: checkbox",
            ]

        if ModelCardSaver._is_apache_model(model_name, terms):
            return ["license: apache-2.0"]

        return []

    @staticmethod
    def _layout_sentence(bits: int | None) -> str:
        sentence = "It uses the mflux/MLX saved-weight layout."
        if bits is not None:
            sentence += " Quantized checkpoints include MLX quantization tensors."
        return sentence + " It is not a Diffusers or Transformers `from_pretrained()` checkpoint."

    @staticmethod
    def _license_section(model_name: str, terms: str, bits: int | None) -> list[str]:
        if ModelCardSaver._is_fibo_model(model_name, terms):
            derivative = "prepared derivative" if bits is None else "quantized derivative"
            return [
                "## License and Access",
                "",
                (
                    f"This checkpoint is a {derivative} of the gated `briaai/FIBO` source model "
                    "and follows the source model's `bria-fibo` non-commercial license terms."
                ),
                "",
                "Host this derivative as a gated Hugging Face repository and require users to accept "
                "the upstream FIBO terms before accessing the files.",
            ]

        if ModelCardSaver._is_flux2_9b(model_name, terms):
            return [
                "## License and Access",
                "",
                (
                    "This checkpoint is a quantized derivative of a gated "
                    "Black Forest Labs FLUX.2 Klein 9B source model. The source model is "
                    f"distributed under the [{ModelCardSaver.FLUX_NON_COMMERCIAL_LICENSE_DISPLAY_NAME}]"
                    f"({ModelCardSaver._flux_noncommercial_license_link(model_name)})."
                ),
                "",
                (
                    "Host this derivative as a gated Hugging Face repository and require users "
                    "to accept the same non-commercial license terms and "
                    f"[Black Forest Labs Acceptable Use Policy]({ModelCardSaver.FLUX_ACCEPTABLE_USE_POLICY_LINK}) "
                    "before accessing the files."
                ),
            ]

        if ModelCardSaver._is_apache_model(model_name, terms):
            derivative = "prepared derivative" if bits is None else "quantized derivative"
            return [
                "## License and Access",
                "",
                f"This {derivative} follows the Apache 2.0 license of the source model.",
            ]

        return []

    @staticmethod
    def _quantization_section(terms: str, bits: int | None) -> str:
        if bits == 8 and "fibo" in terms:
            return "\n".join(
                [
                    "This is an MLX mixed q8/BF16 checkpoint for base FIBO text-to-image generation:",
                    "",
                    "- q8 for quantizable FIBO transformer and text-encoder linears.",
                    "- BF16 for the FIBO VAE.",
                    "- BF16 for FIBO conditioning, timestep, caption-projection, normalization, "
                    "and output-projection paths that are precision-sensitive in MLX-Gen.",
                    "",
                    f"See the [MLX-Gen quantization docs]({ModelCardSaver.QUANTIZATION_DOC_URL}) "
                    "for compatibility notes and measured FIBO behavior.",
                ]
            )

        if bits == 4 and "fibo" in terms:
            return "\n".join(
                [
                    "This is an MLX mixed q4/BF16 checkpoint for base FIBO text-to-image generation:",
                    "",
                    "- q4 for quantizable FIBO transformer and text-encoder linears.",
                    "- BF16 for the FIBO VAE.",
                    "- BF16 for FIBO conditioning, timestep, caption-projection, normalization, "
                    "and output-projection paths that are precision-sensitive in MLX-Gen.",
                    "",
                    f"See the [MLX-Gen quantization docs]({ModelCardSaver.QUANTIZATION_DOC_URL}) "
                    "for compatibility notes and measured FIBO behavior.",
                ]
            )

        if bits == 4 and "qwen" in terms:
            return "\n".join(
                [
                    "This is a mixed q4/q8 checkpoint for Qwen Image generation and editing. "
                    "Fully q4 Qwen checkpoints can lose coherent generative behavior, so MLX-Gen "
                    "uses a mixed policy:",
                    "",
                    "- q4 for most Qwen transformer attention, feed-forward, and projection linears.",
                    "- q8 for Qwen `*.img_mod_linear` transformer modulation layers.",
                    "- q4 for group64-compatible Qwen text-encoder language linears.",
                    "- q8 for group64-compatible Qwen text-encoder visual linears.",
                    "- BF16 for the VAE, norms, embeddings, and linears that are not MLX group64-compatible.",
                    "",
                    f"See the [MLX-Gen quantization docs]({ModelCardSaver.QUANTIZATION_DOC_URL}) "
                    "for the current mixed q4/q8 policy and compatibility notes.",
                ]
            )

        if bits == 4 and "ernie" in terms:
            return "\n".join(
                [
                    "This is an MLX mixed q4/q8 checkpoint for ERNIE Image Turbo. Fully q4 "
                    "ERNIE checkpoints can drift from BF16/q8 behavior, so MLX-Gen uses a "
                    "model-specific mixed policy:",
                    "",
                    "- q4 for ERNIE transformer Q/K attention projections and feed-forward modules.",
                    "- q8 for ERNIE transformer V/O attention projections.",
                    "- q8 for ERNIE text projection, timestep embedding, AdaLN modulation, final norm, and final projection.",
                    "- q8 for Mistral3 text-encoder and Prompt Enhancer linears.",
                    "- q8 for quantizable ERNIE VAE attention modules.",
                    "- BF16 for norms, convolutions, and other non-quantizable parameters.",
                    "",
                    f"See the [MLX-Gen quantization docs]({ModelCardSaver.QUANTIZATION_DOC_URL}) "
                    "for compatibility notes and measured ERNIE q4/q8 behavior.",
                    "",
                    "Prepared ERNIE folders contain the ordinary text-to-image generation stack. "
                    "ERNIE Prompt Enhancer files are not bundled in this checkpoint.",
                ]
            )

        if bits == 8 and "ernie" in terms:
            return "\n".join(
                [
                    "This is an MLX q8 checkpoint for ERNIE Image Turbo. MLX-Gen uses "
                    "8-bit quantization for ERNIE modules where MLX supports quantization:",
                    "",
                    "- q8 for quantizable ERNIE transformer modules.",
                    "- q8 for quantizable ERNIE text-encoder modules.",
                    "- q8 for quantizable ERNIE VAE attention modules.",
                    "- BF16 for norms, convolutions, and other non-quantizable parameters.",
                    "",
                    "ERNIE q4 uses a model-specific mixed q4/q8 policy because fully q4 "
                    "checkpoints can drift from BF16/q8 behavior.",
                    "",
                    f"See the [MLX-Gen quantization docs]({ModelCardSaver.QUANTIZATION_DOC_URL}) "
                    "for compatibility notes and measured ERNIE q4/q8 behavior.",
                    "",
                    "Prepared ERNIE folders contain the ordinary text-to-image generation stack. "
                    "ERNIE Prompt Enhancer files are not bundled in this checkpoint.",
                ]
            )

        if bits == 8 and "wan" in terms:
            wan_label = ModelCardSaver._wan_model_label(terms)
            return "\n".join(
                [
                    f"This is an MLX q8 checkpoint for {wan_label}. It is a mixed q8/BF16 package: "
                    "MLX-Gen uses 8-bit quantization for Wan modules where MLX supports quantization, "
                    "and preserves runtime-sensitive or unsupported paths at BF16:",
                    "",
                    "- q8 for quantizable Wan transformer attention and feed-forward modules.",
                    "- BF16 for the Wan VAE.",
                    "- BF16 for Wan transformer conditioning/output projection linears, the UMT5 text encoder, "
                    "scheduler metadata, tokenizer files, norms, convolutions, and other non-quantizable parameters.",
                    "",
                    "Wan q4 quality and any possible mixed q4/q8 policy are still under validation. "
                    "Prefer q8 for publishable Wan checkpoints until the q4 policy is documented.",
                    "",
                    f"See the [MLX-Gen quantization docs]({ModelCardSaver.QUANTIZATION_DOC_URL}) "
                    "for compatibility notes.",
                ]
            )

        if bits == 4 and "wan" in terms:
            wan_label = ModelCardSaver._wan_model_label(terms)
            return "\n".join(
                [
                    f"This is an experimental MLX 4-bit checkpoint for {wan_label}. Wan q4 quality is still "
                    "under validation in MLX-Gen; do not treat this checkpoint as equivalent to BF16/q8 unless "
                    "side-by-side video tests confirm acceptable motion and visual quality.",
                    "",
                    "Prefer q8 for publishable Wan checkpoints until the Wan q4 or mixed q4/q8 policy is documented.",
                    "",
                    f"See the [MLX-Gen quantization docs]({ModelCardSaver.QUANTIZATION_DOC_URL}) "
                    "for compatibility notes.",
                ]
            )

        if bits is None and "wan" in terms:
            wan_label = ModelCardSaver._wan_model_label(terms)
            return "\n".join(
                [
                    f"This checkpoint stores MLX-Gen {wan_label} weights without an explicit quantization level.",
                    "",
                    "For Wan checkpoints, MLX-Gen loads transformer and VAE weights at BF16 runtime precision. "
                    "The UMT5 text encoder is preserved from the source model. Wan supports text-to-video and "
                    "selected image-to-video routes depending on the source model.",
                ]
            )

        if bits is None and "ernie" in terms:
            return (
                "This checkpoint stores MLX-Gen ERNIE Image Turbo generation weights without an explicit "
                "quantization level. Prepared ERNIE folders contain the ordinary text-to-image generation "
                "stack; ERNIE Prompt Enhancer files are not bundled in this checkpoint."
            )

        if bits is None and "fibo" in terms:
            return (
                "This checkpoint stores MLX-Gen base FIBO text-to-image weights without an explicit "
                "quantization level. FIBO Edit is a separate source model and is not bundled."
            )

        if bits is not None and "seedvr2" in terms:
            seedvr2_label = ModelCardSaver._seedvr2_model_label(terms)
            return "\n".join(
                [
                    f"This is an MLX {bits}-bit checkpoint for {seedvr2_label} image super-resolution.",
                    "",
                    f"- q{bits} for quantizable SeedVR2 transformer linears and VAE attention linears.",
                    "- BF16 for convolutions, normalization layers, and other non-quantizable parameters.",
                    "- MLX-Gen supplies the static SeedVR2 positive embedding at runtime when the prepared checkpoint does not bundle it.",
                    "",
                    f"See the [MLX-Gen quantization docs]({ModelCardSaver.QUANTIZATION_DOC_URL}) "
                    "for compatibility notes and measured behavior.",
                ]
            )

        if bits is None and "seedvr2" in terms:
            seedvr2_label = ModelCardSaver._seedvr2_model_label(terms)
            return (
                f"This checkpoint stores MLX-Gen {seedvr2_label} image super-resolution weights without "
                "an explicit quantization level."
            )

        if bits == 8:
            section = (
                "This is an MLX q8 checkpoint. Quantizable modules are saved at 8-bit where "
                "the model layout supports MLX quantization; VAE weights and non-quantizable "
                "layers remain BF16."
            )
            if "qwen" in terms:
                section += (
                    " The Qwen-specific mixed q4/q8 policy only applies when preparing Qwen models "
                    f"with `--quantize 4`; see the [MLX-Gen quantization docs]({ModelCardSaver.QUANTIZATION_DOC_URL})."
                )
            return section

        if bits is not None:
            return (
                f"This is an MLX {bits}-bit checkpoint. Model-specific quantization predicates "
                "may keep unsupported layers unquantized or at a different precision. "
                f"See the [MLX-Gen quantization docs]({ModelCardSaver.QUANTIZATION_DOC_URL}) "
                "for compatibility notes."
            )

        return "This checkpoint stores MLX-Gen weights without an explicit quantization level."

    @staticmethod
    def _source_model_line(model_name: str) -> str:
        if ModelCardSaver._is_huggingface_repo_id(model_name):
            return f"Original model: [`{model_name}`](https://huggingface.co/{model_name})."
        return f"Original model reference: `{model_name}`."

    @staticmethod
    def _usage_note(terms: str, bits: int | None) -> list[str]:
        if "wan" in terms and "a14b" in terms and bits == 8:
            return [
                "The q8 A14B example below is intentionally validation-sized. Do not use this card to claim "
                "full-size `1280x720`, 81-frame, 40-step readiness until that exact path has passed video "
                "integrity and quality validation.",
                "",
                "The measured A14B memory rows in the MLX-Gen quantization docs are short low-RAM profiles "
                "on an Apple M5 Max with 128 GiB unified memory. `Physical Peak` is full-process Darwin "
                "physical footprint, `Max RSS` can under-report Apple unified-memory/Metal pressure, and "
                "`MLX Peak` is only the MLX allocator high-water mark.",
                "",
            ]
        if "wan" in terms and "a14b" in terms:
            return [
                "The usage command below is a recommended full-size Wan A14B shape. The measured memory "
                "rows in the MLX-Gen quantization docs are separate short low-RAM validation profiles.",
                "",
                "For memory tables: `Physical Peak` is full-process Darwin physical footprint, `Max RSS` "
                "can under-report Apple unified-memory/Metal pressure, and `MLX Peak` is only the MLX "
                "allocator high-water mark.",
                "",
            ]
        return []

    @staticmethod
    def _command_surface_line(terms: str) -> str:
        if "seedvr2" in terms:
            return "Use `mlxgen download` and `mlxgen upscale` for this SeedVR2 package."
        return "Use the `mlxgen` command and Python import path for new MLX-Gen projects."

    @staticmethod
    def _usage_block(repo_id: str, pipeline_tag: str, terms: str, bits: int | None) -> list[str]:
        if "seedvr2" in terms:
            return [
                "```bash",
                "python -m pip install -U mlx-gen",
                "",
                f"mlxgen download --model {repo_id}",
                "",
                "mlxgen upscale \\",
                f"  --model {repo_id} \\",
                "  --image-path input.png \\",
                "  --resolution 2x \\",
                "  --seed 42 \\",
                "  --metadata \\",
                "  --output upscaled.png",
                "```",
            ]
        return [
            "```bash",
            "python -m pip install -U mlx-gen",
            "",
            f"mlxgen download --model {repo_id}",
            "",
            "mlxgen generate \\",
            f"  --model {repo_id} \\",
            *ModelCardSaver._usage_lines(pipeline_tag, terms, bits),
            "```",
        ]

    @staticmethod
    def _usage_lines(pipeline_tag: str, terms: str, bits: int | None) -> list[str]:
        if "wan" in terms:
            if ModelCardSaver._wan_is_i2v_only(terms):
                return [
                    "  --image input.png \\",
                    '  --prompt "Your video prompt here" \\',
                    *(
                        ["  --width 384 \\", "  --height 384 \\"]
                        if bits == 8 and "a14b" in terms
                        else ["  --width 224 \\", "  --height 384 \\"]
                    ),
                    "  --frames 33 \\",
                    "  --steps 12 \\",
                    "  --guidance 3.5 \\",
                    "  --guidance-2 3.5 \\",
                    "  --fps 8 \\",
                    "  --seed 4242 \\",
                    *(
                        ["  --low-ram \\"]
                        if bits == 8 and "a14b" in terms
                        else []
                    ),
                    "  --metadata \\",
                    "  --output video.mp4",
                ]
            if "a14b" in terms:
                if bits == 8:
                    return [
                        '  --prompt "Your video prompt here" \\',
                        "  --width 384 \\",
                        "  --height 224 \\",
                        "  --frames 33 \\",
                        "  --steps 12 \\",
                        "  --guidance 4 \\",
                        "  --guidance-2 3 \\",
                        "  --fps 8 \\",
                        "  --seed 4242 \\",
                        "  --low-ram \\",
                        "  --metadata \\",
                        "  --output video.mp4",
                    ]
                return [
                    '  --prompt "Your video prompt here" \\',
                    "  --width 1280 \\",
                    "  --height 720 \\",
                    "  --frames 81 \\",
                    "  --steps 40 \\",
                    "  --guidance 4 \\",
                    "  --guidance-2 3 \\",
                    "  --fps 16 \\",
                    "  --seed 42 \\",
                    "  --output video.mp4",
                ]
            return [
                '  --prompt "Your video prompt here" \\',
                "  --width 1280 \\",
                "  --height 704 \\",
                "  --frames 121 \\",
                "  --steps 50 \\",
                "  --guidance 5 \\",
                "  --fps 24 \\",
                "  --seed 42 \\",
                "  --output video.mp4",
            ]

        if pipeline_tag == "image-to-image":
            return [
                "  --image path_to_image.png \\",
                '  --prompt "Your edit prompt here" \\',
                "  --steps 20 \\",
                "  --seed 42 \\",
                "  --output edited.png",
            ]

        if "z-image-turbo" in terms or "zimage-turbo" in terms:
            return [
                '  --prompt "Your prompt here" \\',
                "  --steps 8 \\",
                "  --guidance 0 \\",
                "  --seed 42 \\",
                "  --output image.png",
            ]

        if "ernie-image-turbo" in terms or "ernie" in terms:
            return [
                '  --prompt "Your prompt here" \\',
                "  --width 512 \\",
                "  --height 512 \\",
                "  --steps 8 \\",
                "  --guidance 1 \\",
                "  --seed 42 \\",
                "  --output image.png",
            ]

        if "z-image" in terms or "zimage" in terms:
            return [
                '  --prompt "Your prompt here" \\',
                "  --steps 50 \\",
                "  --guidance 4 \\",
                "  --seed 42 \\",
                "  --output image.png",
            ]

        return [
            '  --prompt "Your prompt here" \\',
            "  --steps 20 \\",
            "  --seed 42 \\",
            "  --output image.png",
        ]

    @staticmethod
    def _tags(terms: str, bits: int | None, pipeline_tag: str) -> list[str]:
        tags = ["mlx", "mlx-gen", "mflux", "apple-silicon"]
        if bits is not None:
            tags.append(f"{bits}-bit")
        if bits == 4 and ("qwen" in terms or "ernie" in terms):
            tags.extend(["mixed-q4", "mixed-q4-q8"])
        if bits == 8 and "wan" in terms:
            tags.append("mixed-q8-bf16")
        if bits == 4 and "fibo" in terms:
            tags.append("mixed-q4-bf16")
        if bits == 8 and "fibo" in terms:
            tags.append("mixed-q8-bf16")
        if "qwen" in terms:
            tags.extend(["qwen", "qwen-image"])
        if ("edit" in terms or pipeline_tag == "image-to-image") and "seedvr2" not in terms:
            tags.append("image-editing")
        if "flux" in terms:
            tags.append("flux")
        if "flux2" in terms or "flux.2" in terms:
            tags.append("flux2")
        if "z-image" in terms or "zimage" in terms:
            tags.append("z-image")
        if "ernie" in terms:
            tags.extend(["ernie", "ernie-image", "ernie-image-turbo"])
        if "wan" in terms:
            tags.extend(["wan", "wan2.2", "video-generation"])
            if ModelCardSaver._wan_supports_text_to_video(terms):
                tags.append("text-to-video")
            if ModelCardSaver._wan_supports_image_to_video(terms):
                tags.append("image-to-video")
            if "a14b" in terms:
                tags.append("wan-a14b")
        if "fibo" in terms:
            tags.append("fibo")
        if "seedvr2" in terms:
            tags.extend(["seedvr2", "image-upscaling", "super-resolution"])
        return ModelCardSaver._deduplicate(tags)

    @staticmethod
    def _pipeline_tag(terms: str) -> str:
        if "wan" in terms:
            if ModelCardSaver._wan_is_i2v_only(terms):
                return "image-to-video"
            return "text-to-video"
        if "seedvr2" in terms:
            return "image-to-image"
        if any(term in terms for term in ("edit", "kontext", "fill", "depth", "controlnet", "redux")):
            return "image-to-image"
        return "text-to-image"

    @staticmethod
    def _model_terms(model: Any) -> str:
        model_config = getattr(model, "model_config", None)
        values = [
            getattr(model_config, "model_name", ""),
            getattr(model_config, "base_model", ""),
            model.__class__.__name__,
        ]
        values.extend(getattr(model_config, "aliases", []) or [])
        return " ".join(str(value) for value in values if value).lower()

    @staticmethod
    def _wan_model_label(terms: str) -> str:
        if "a14b" in terms:
            return "Wan2.2 A14B"
        if "ti2v" in terms or "5b" in terms:
            return "Wan2.2 TI2V-5B"
        return "Wan2.2"

    @staticmethod
    def _seedvr2_model_label(terms: str) -> str:
        if "7b" in terms:
            return "SeedVR2 7B"
        return "SeedVR2 3B"

    @staticmethod
    def _wan_supports_text_to_video(terms: str) -> bool:
        return not ModelCardSaver._wan_is_i2v_only(terms)

    @staticmethod
    def _wan_supports_image_to_video(terms: str) -> bool:
        return ModelCardSaver._wan_is_ti2v_model(terms) or ModelCardSaver._wan_is_i2v_only(terms)

    @staticmethod
    def _wan_is_i2v_only(terms: str) -> bool:
        if any(token in terms for token in ("i2v-a14b", "i2v_a14b", "a14b-i2v", "a14b_i2v")):
            return True
        return "i2v" in terms and "ti2v" not in terms

    @staticmethod
    def _wan_is_ti2v_model(terms: str) -> bool:
        return any(token in terms for token in ("ti2v-5b", "ti2v_5b", "5b-ti2v", "5b_ti2v"))

    @staticmethod
    def _contributor_line(bits: int | None) -> str:
        action = "Prepared" if bits is None else "Quantized"
        return f"{action} and contributed by {ModelCardSaver.CONTRIBUTOR}."

    @staticmethod
    def _model_name(model: Any) -> str:
        model_config = getattr(model, "model_config", None)
        return str(getattr(model_config, "model_name", "unknown-model"))

    @staticmethod
    def _repo_name(model_name: str) -> str:
        return Path(model_name).name.lower().replace("_", "-")

    @staticmethod
    def _is_huggingface_repo_id(model_name: str) -> bool:
        return "/" in model_name and model_name.count("/") == 1 and not model_name.startswith(("./", "../", "~/"))

    @staticmethod
    def _is_flux2_9b(model_name: str, terms: str) -> bool:
        normalized = f"{model_name} {terms}".lower()
        return "flux.2-klein" in normalized and "9b" in normalized

    @staticmethod
    def _is_fibo_model(model_name: str, terms: str) -> bool:
        normalized = f"{model_name} {terms}".lower()
        return "fibo" in normalized

    @staticmethod
    def _flux_noncommercial_license_link(model_name: str) -> str:
        if ModelCardSaver._is_huggingface_repo_id(model_name):
            return f"https://huggingface.co/{model_name}/blob/main/LICENSE.md"
        return ModelCardSaver.FLUX_NON_COMMERCIAL_LICENSE_LINK

    @staticmethod
    def _fibo_license_link(model_name: str) -> str:
        if ModelCardSaver._is_huggingface_repo_id(model_name):
            return f"https://huggingface.co/{model_name}"
        return "https://huggingface.co/briaai/FIBO"

    @staticmethod
    def _is_apache_model(model_name: str, terms: str) -> bool:
        normalized = f"{model_name} {terms}".lower()
        return (
            "qwen" in normalized
            or "z-image" in normalized
            or "zimage" in normalized
            or "ernie" in normalized
            or "wan" in normalized
            or "seedvr2" in normalized
            or ("flux.2-klein" in normalized and "4b" in normalized)
        )

    @staticmethod
    def _deduplicate(values: list[str]) -> list[str]:
        seen = set()
        result = []
        for value in values:
            if value in seen:
                continue
            seen.add(value)
            result.append(value)
        return result
